bases:
  - ../../bases/example-base

nameSuffix: -lab1

namespace: lab1

resources:
  - namespace.yaml

configMapGenerator:
  - name: specific-vars
    literals:
    - LAB_NAME=one

images:
  - name: messivanio/example
    newTag: 0.0.1-lab1 # {"$imagepolicy": "flux-system:messivanio-example-image-policy-lab1:tag"}
